services:
  app:
    # build image using Dockerfile
    build:
      context: .
      # build stage named dev, see Dockerfile for reference
      target: dev
    container_name: vite-react-ts-app
    image: damianboni/vite:react-ts
    ports:
      # host/container
      - '5173:5173'
    volumes:
      - .:/app
      # blind mount so that host's dir is updated from container
      - /app/node_modules