services:
  app:
    # build image using Dockerfile
    build: .
    container_name: vite-react-ts-app
    image: damianboni:vite-react-ts
    ports:
      # host/container
      - '5173:5173'
    volumes:
      # binds current directory so any file changes will update
      - .:/app
      # volume is set so that container's /node_modules is used rather than host's
      - /app/node_modules